package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'MyVcsRoot'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("MyVcsRoot")) {
    val expected = GitVcsRoot({
        id("MyVcsRoot")
        name = "MyVcsRoot"
        url = "git@github.com:lezuch/anewtodolist.git"
        branch = "refs/heads/main"
        authMethod = uploadedKey {
            uploadedKey = "TC"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        branchSpec = """
            +:refs/heads/(main)
            +:refs/heads/(test)
            +:refs/heads/(test2)
        """.trimIndent()
    }

}
