package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'SpringVsc'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("SpringVsc")) {
    val expected = GitVcsRoot({
        id("SpringVsc")
        name = "SpringVsc"
        url = "git@github.com:lezuch/spring-petclinic.git"
        branch = "refs/heads/main"
        authMethod = uploadedKey {
            uploadedKey = "test"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = uploadedKey {
            userName = ""
            uploadedKey = "TC"
            passphrase = ""
        }
    }

}
